# Book settings
title:
author: Development Data Partnership
logo: docs/images/logo.png

repository:
    url: https://github.com/datapartnership/template
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://datapartnership.github.io/template

only_build_toc_files: true
